# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
start-at-login = true

after-startup-command = [
  'exec-and-forget sketchybar'
]
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[mode.main.binding]
cmd-enter = 'exec-and-forget open -n /Applications/WezTerm.app'
alt-cmd-ctrl-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

alt-cmd-ctrl-left = 'focus left'
alt-cmd-ctrl-down = 'focus down'
alt-cmd-ctrl-up = 'focus up'
alt-cmd-ctrl-right = 'focus right'

alt-cmd-ctrl-shift-left = 'move left'
alt-cmd-ctrl-shift-down = 'move down'
alt-cmd-ctrl-shift-up = 'move up'
alt-cmd-ctrl-shift-right = 'move right'

alt-cmd-ctrl-h = 'split horizontal'
alt-cmd-ctrl-v = 'split vertical'

alt-cmd-ctrl-f = 'fullscreen'

alt-cmd-ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
alt-cmd-ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-cmd-ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-cmd-ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-cmd-ctrl-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-cmd-ctrl-a = 'focus parent'

alt-cmd-ctrl-1 = 'workspace 1'
alt-cmd-ctrl-2 = 'workspace 2'
alt-cmd-ctrl-3 = 'workspace 3'
alt-cmd-ctrl-4 = 'workspace 4'
alt-cmd-ctrl-5 = 'workspace 5'
#alt-cmd-ctrl-6 = 'workspace 6'
#alt-cmd-ctrl-7 = 'workspace 7'
#alt-cmd-ctrl-8 = 'workspace 8'
#alt-cmd-ctrl-9 = 'workspace 9'

alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
alt-cmd-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-cmd-ctrl-shift-5 = 'move-node-to-workspace 5'
#alt-cmd-ctrl-shift-6 = 'move-node-to-workspace 6'
#alt-cmd-ctrl-shift-7 = 'move-node-to-workspace 7'
#alt-cmd-ctrl-shift-8 = 'move-node-to-workspace 8'
#alt-cmd-ctrl-shift-9 = 'move-node-to-workspace 9'

ctrl-left = 'workspace prev'
ctrl-right = 'workspace next'

alt-cmd-ctrl-shift-c = 'reload-config'

alt-cmd-ctrl-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'




